language: php

dist: trusty
sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files
        - .phpunit

env:
    global:
        - SYMFONY_PHPUNIT_DIR=.phpunit
        - SYMFONY_PHPUNIT_VERSION=8.3

matrix:
  fast_finish: true
  include:
    - php: '7.1'
      env: COMPOSER_FLAGS="--prefer-lowest" SYMFONY_DEPRECATIONS_HELPER=weak SYMFONY_PHPUNIT_VERSION=7.5
    # Test against Symfony LTS versions
    - php: '7.1'
      env: SYMFONY_VERSION="3.4.*" SYMFONY_PHPUNIT_VERSION=7.5
    - php: '7.2'
    - php: '7.3'
    # Test against dev versions
    - php: '7.4snapshot'
      env: DEPENDENCIES=dev
  allow_failures:
    - env: DEPENDENCIES=dev

before_install:
    - composer self-update
    - if [ "$DEPENDENCIES" = "dev" ]; then composer config minimum-stability dev; fi;
    - if [ "$DEPENDENCIES" = "dev" ]; then pecl install xdebug-beta; fi;
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony:"$SYMFONY_VERSION"; fi

install:
    - composer update $COMPOSER_FLAGS
    - ./vendor/bin/simple-phpunit install

script: ./vendor/bin/simple-phpunit -v --coverage-text
